### ISSUE TITLE
Possibly wrong joint effort definitions

### ISSUE THREAD

**Issue by ferrolho** [ipab-slmc/kuka_lwr4_description#11]
All the KUKA joint efforts seem to be set to either `306` or `204`:
https://github.com/ipab-slmc/kuka_lwr4_description/blob/1a5483a932108138b4566d46fbf6ae291f0b7aff/urdf/defs/kuka_lwr_arm_defs.urdf.xacro#L92

These seem suspiciously high. I'll try to get the hold of the user manual from the lab to crosscheck them.

**Comment by wxmerkt** [comment]
This is wrong indeed - our URDFs are based on some super early definitions from another lab. Here are the joint torque limits from the LWR 4+ datasheet:

![image](https://user-images.githubusercontent.com/1664508/56316870-55badc00-6153-11e9-859b-9cc71caa420c.png)

Source: https://www.kukakore.com/wp-content/uploads/2012/07/KUKA_LBR4plus_ENLISCH.pdf
